name: agradiance_flutter_drive
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  jiffy: ^6.4.3
  flutter_form_builder: ^10.1.0
  lite_validator: ^0.0.4
  responsive_framework: ^1.5.1
  flutter_tts: ^4.2.3
  share_plus: ^11.0.0
  dio: ^5.8.0+1
  http_status: ^3.3.3
  flutter_local_notifications: ^19.3.0
  collection: ^1.19.1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  file_saver: ^0.3.1
  device_info_plus: ^11.5.0
  country_picker: ^2.0.27
  google_mobile_ads: ^6.0.0
  app_links: ^6.4.0
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  new_version_plus: ^0.1.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.0
  readmore: ^3.0.0
  dart_jsonwebtoken: ^3.1.1
  dlibphonenumber: ^1.1.42
  encrypt: ^5.0.3
  loading_animation_widget: ^1.3.0
  skeletonizer: ^2.1.0+1
  cached_network_image: ^3.4.1
  extended_image: ^10.0.1
  visibility_detector: ^0.4.0+2
  elegant_theme: ^0.2.2
  toastification: ^3.0.3
  firebase_messaging: ^16.0.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/icon/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
